"use client";

import { Download } from "lucide-react";
import { Shell } from "../../components/Shell";
import { downloadExport } from "../../lib/api";

export default function ExportsPage() {
  const params = new URLSearchParams();
  return (
    <Shell title="Exports">
      <div className="rounded border border-zinc-200 bg-white p-5">
        <h2 className="mb-2 font-semibold">Full inventory export</h2>
        <p className="mb-4 text-sm text-zinc-600">Exports are generated by the backend API so the frontend never connects to MySQL.</p>
        <div className="flex flex-wrap gap-3">
          <button className="btn" onClick={() => downloadExport("/exports/inventory.csv", params, "inventory-export.csv")}><Download className="h-4 w-4" /> Download CSV</button>
          <button className="btn-secondary" onClick={() => downloadExport("/exports/inventory.xlsx", params, "inventory-export.xlsx")}><Download className="h-4 w-4" /> Download XLSX</button>
        </div>
      </div>
    </Shell>
  );
}
